version: '3.8'
services:
  app:
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/src/app/
    ports:
      - '8080:8080'
    depends_on:
      - MySql

  MySql:
    container_name: GreenvaultDb
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'

volumes:
  mysql:
